// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRIrGGGgtIXmnHpMgIq91CvKazVUfCmPE',
    appId: '1:503515973126:web:5f07e05cbe30116845e587',
    messagingSenderId: '503515973126',
    projectId: 'smart-expense-tracker-370b7',
    authDomain: 'smart-expense-tracker-370b7.firebaseapp.com',
    storageBucket: 'smart-expense-tracker-370b7.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXvovVPpEDnj6ntbF7MbJQAboxN64ghJs',
    appId: '1:503515973126:android:5bb77bf0036582e045e587',
    messagingSenderId: '503515973126',
    projectId: 'smart-expense-tracker-370b7',
    storageBucket: 'smart-expense-tracker-370b7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzqTVppkXAgEfB839QDuuQ4HvTbqS-4BU',
    appId: '1:503515973126:ios:9ba5de346c7b999f45e587',
    messagingSenderId: '503515973126',
    projectId: 'smart-expense-tracker-370b7',
    storageBucket: 'smart-expense-tracker-370b7.firebasestorage.app',
    iosBundleId: 'com.example.smartExpenseTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDzqTVppkXAgEfB839QDuuQ4HvTbqS-4BU',
    appId: '1:503515973126:ios:9ba5de346c7b999f45e587',
    messagingSenderId: '503515973126',
    projectId: 'smart-expense-tracker-370b7',
    storageBucket: 'smart-expense-tracker-370b7.firebasestorage.app',
    iosBundleId: 'com.example.smartExpenseTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCRIrGGGgtIXmnHpMgIq91CvKazVUfCmPE',
    appId: '1:503515973126:web:a1e350d25319f6c745e587',
    messagingSenderId: '503515973126',
    projectId: 'smart-expense-tracker-370b7',
    authDomain: 'smart-expense-tracker-370b7.firebaseapp.com',
    storageBucket: 'smart-expense-tracker-370b7.firebasestorage.app',
  );
}
